- ps: |
    # init:
    # Parse commit message, set env variable conditional
    if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match '\[release\]') { 
        $env:deploy_github_releases = "true" 
    } else { 
        $env:deploy_github_releases = "false" 
    }
    echo "deploy_github_releases: $env:deploy_github_releases"